### ISSUE TITLE
Laravel 4 Support?

### ISSUE THREAD

**Issue by VerzatileTom** [ktquez/laravel-tinymce#1]
I tried it to laravel 4, I cannot force publish the configuration because it requires for a facade. But, ignore it anyway just to find out if it works and it doesn't work for me. Do you have a laravel 4 support for this?

**Comment by ktquez** [comment]
Sorry, not at the moment, only from version 5.
Because I started with Laravel from there, however I think it works if you follow what works in Lumen, without using the publish by copying the folder manually.
