### ISSUE TITLE
The configuration file is breaking the artisan command

### ISSUE THREAD

**Issue by avidenov** [ktquez/laravel-tinymce#2]
On Laravel 5.1 the

```php
'cdn' => url('vendor/js/tinymce/tinymce.min.js'),
```

is breaking the artisan command by calling the `url()` method before it is available.

Updating the code to use the `app.url` config should fix this problem:

```php
'cdn' => Config('app.url').'/vendor/js/tinymce/tinymce.min.js'
```

**Comment by ktquez** [comment]
Hi @avidenov!
Fixed, thanks a lot!

**Comment by RagingAlcoholic** [comment]
Just a quick note:

If testing on local host, `Config('app.url')` will leave out the port number which results in a failure to grab the javascript file. So if you're running 5.2 locally on port 8000 it should look something like this:

`'cdn' => Config('app.url').':8000/vendor/js/tinymce/tinymce.min.js'`

**Comment by brynnbp** [comment]
@RagingAlcoholic  thanks, I was having this same problem. This should probably be re-opened.

**Comment by avidenov** [comment]
There are couple of problems with adding the port to the URL
* You need to change it before production, which is something that you can often miss.
* Different setups require different port so it is not a solution that will work in every case.

Maybe consider some virtual hosts for your localhost setup would be better?

**Comment by unarist** [comment]
@ktquez A recent commit ec6e4b17 seems to break this again.

**Comment by javougarte** [comment]
I just changed

> 'cdn' => url('vendor/js/tinymce/tinymce.min.js')

for

> 'cdn' => '/vendor/js/tinymce/tinymce.min.js'

and it seems to work nicely.
