### ISSUE TITLE
Load programatically

### ISSUE THREAD

**Issue by LastTemplar** [ktquez/laravel-tinymce#3]
Is it possible to load the editor programatically instead of using "@include('tinymce::tpl')" ?
I have two textareas in my view and I want each of them to have different configs.

**Comment by mwhardesty** [comment]
I'm also interested in this answer. Right now, I have 3 textareas on my page, but I can only get the first to display the TinyMCE editor.

**Comment by ktquez** [comment]
This coming weekend, will give an update in this package, and leave it with more flexibility, for more than one textarea, optimize the config file and the version of tinymce.

**Comment by ktquez** [comment]
I gave an extended in the settings and you can now use a custom configuration for each textarea, however the only thing that is unique to all, is the texarea theme, but other settings can remain personalized.

v1.0.1

---

I will develop a more elaborate package, trying to bring a better use of TinyMCE in our projects and achieve greater performance, having seen that this tool is part of the front end and not necessarily the backend had to take care of it, however, facilitates integration quickly and help those who have no knowledge in broad front.
