### ISSUE TITLE
Handling onkeyup events?

### ISSUE THREAD

**Issue by WesThorburn** [ktquez/laravel-tinymce#7]
How can I configure a custom textarea so that a particular Javascript function is called on each onkeyup event?

A lot of the TinyMCE 4 code examples I've found recommend modifying tinymce.init and adding the following code:
```
setup: function(ed) {
    ed.on('keyup', function(e) {
        console.log('onkeyup event detected, this is the textarea contents: ' + ed.getContent());
        check_submit();
    });
}
```
Adding this to the config/tinymce.php doesn't work. What is the correct way to achieve this?

**Comment by WesThorburn** [comment]
I solved this by removing all of the custom configuration from config/tincymce.php and putting it into the view instead. 

In the view, I removed the @include('tinymce::tpl', ['els' => ['customMCE']]) statement and replaced it with the following:
```
<script type="text/javascript" src="http://localhost:8000/vendor/js/tinymce/tinymce.min.js"></script>

<script type="text/javascript">
	tinymce.init({
		"selector":"#solution",
		"height":"450px",
		"language":"en",
		"theme":"modern",
		"skin":"lightgray",
		"menubar":"",
		"plugins":["advlist autolink link image lists charmap hr anchor pagebreak","searchreplace wordcount visualblocks visualchars fullscreen insertdatetime nonbreaking","save table contextmenu directionality template paste"],
		"toolbar":"undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist",
		"setup":function(ed) {
				    ed.on('keyup', function(e) {
				       console.log('onkeyup event detected, this is the textarea contents: ' + ed.getContent());
				   });
			}
		});
				
 </script>
```
Notice how I added the "setup" variable with its corresponding function into the tinymce.init array. The TinyMCE textarea renders perfectly and keyup events are now detected correctly.

It'd be great if I could just add the "setup" variable directly to the custom configuration array in config/tinymce.php and didn't have to move it all to the view.

**Comment by ktquez** [comment]
@WesThorburn 
What good have temporarily resolved, so I fix this, I warn you here, ok.
